<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<RazorCompileOnBuild>true</RazorCompileOnBuild>
		<RazorEmbeddedResource>true</RazorEmbeddedResource>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.0" />
		<PackageReference Include="DNTCaptcha.Core" Version="5.3.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EHRIS.Core\EHRIS.Core.csproj" />
		<ProjectReference Include="..\EHRIS.Security\EHRIS.Security.csproj" />
		<ProjectReference Include="..\EHRIS.Services\EHRIS.Services.csproj" />
		<ProjectReference Include="..\EHRIS.Tools\EHRIS.Tools.csproj" />
		<ProjectReference Include="..\EHRIS.Web.Shared\EHRIS.Web.Shared.csproj" />
	</ItemGroup>

</Project>
