<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Email\IMailAccountService.cs" />
    <Compile Remove="Email\IMailSettingsProvider.cs" />
    <Compile Remove="Email\MailAccountService.cs" />
    <Compile Remove="Email\MailSettingsProvider.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="GemBox.Spreadsheet" Version="2025.12.105" />
    <PackageReference Include="Isopoh.Cryptography.Argon2" Version="2.0.0" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.3" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.1" />
    <PackageReference Include="MimeKit" Version="4.15.1" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="BouncyCastle.Crypto">
      <Aliases>CryptoLegacy</Aliases>
      <Private>true</Private>
    </Reference>
    <Reference Include="BouncyCastle.Cryptography">
      <Aliases>CryptoNew</Aliases>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
