<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Service\**" />
    <EmbeddedResource Remove="Service\**" />
    <None Remove="Service\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.1" />
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>

    <Content Include="appsettings.json">
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EHRIS.Core\EHRIS.Core.csproj" />
    <ProjectReference Include="..\EHRIS.Services\EHRIS.Services.csproj" />
    <ProjectReference Include="..\EHRIS.Tools\EHRIS.Tools.csproj" />
  </ItemGroup>

</Project>
